name: Baseline profile generation

on:
  # every day at 00:43
  schedule:
    - cron: '43 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  baseline-profile:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      TERM: dumb

    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        token: ${{ secrets.POST_RELEASE_GH_TOKEN }}
        fetch-depth: 0
 
    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: 18

    - name: Set up Git author
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Setup Gradle caching
      uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: true

    - name: Decrypt secrets
      run: |
        ./scripts/setup-age.sh
        ./scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    # This allows us to build most of what we need without the emulator running
    # and using resources
    - name: Build app and benchmark
      run: ./gradlew :benchmark:assembleNonMinifiedBenchmark :android:assembleNonMinifiedRelease

    - name: Setup emulator for benchmark
      run: ./gradlew :benchmark:api31Setup

    - name: Run benchmark on Gradle Managed Device
      run: |
        ./gradlew cleanManagedDevices
        ./gradlew generateBaselineProfile \
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

    # If we're on main branch, commit the baseline profile to the repository (if changed)
    - name: Commit baseline profile into main
      if: github.ref == 'refs/heads/main'
      run: |
        # If the baseline profile has changed, commit it
        if [[ $(git diff --stat android/src/main/generated/baselineProfiles/baseline-prof.txt) != '' ]]; then
          git add android/src/main/generated/baselineProfiles/baseline-prof.txt
          git commit -m "chore(android): refresh baseline profile" && git push
        fi

    - name: Clean secrets
      if: always()
      run: scripts/signing-cleanup.sh
