name: Deploy snapshot builds

on:
  push:
    branches:
      - main

jobs:
  deploy-release-snapshot:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Setup Java 16
      uses: actions/setup-java@d9126d7df2f1b080b603441eaf5810ced3614e78
      with:
        distribution: 'zulu'
        java-version: '16'

    - name: Checkout repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Decrypt secrets
      run: scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Build release app
      uses: burrunan/gradle-cache-action@03c71a8ba93d670980695505f48f49daf43704a6
      with:
        arguments: :android:assembleRelease

    - name: Clean secrets
      run: scripts/signing-cleanup.sh

    - name: Deploy snapshot
      run: scripts/deploy-snapshot.sh
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
