name: Qodana

on:
  workflow_dispatch:
  schedule:
    - cron: "20 3 * * 0"

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@3fdeefa830a7634a5c04f1cd70fcfb69956137a2 # v2022.3.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
