name: Qodana

on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@c25ee7dc4d0697b27ac54877a4ff71cf5b6dde3c # v2022.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
